[build]
  base = "/"
  publish = "public/"
  command = "npm run build"

[context.production]
  command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://jinhang.netlify.app/*"
  to = "https://jinhang.work/:splat"
  status = 301
  force = true